spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1q2w3e$R
  jpa:
    show-sql: true # mysql debug mode, 실제 쿼리가 로그로 보임
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate: # custom options
        format_sql: true # sql 로그를 포매팅해서 보여줌
logging:
  level:
    org.hibernate.type: trace # bind 쿼리의 내용까지 출력. ? 부분이 실제 값으로 표현됨
server:
  port: 8080